/**
 * Seed dishes — hand-curated Indian home-kitchen library.
 *
 * Canonical source of truth for the dish catalog (generates the SQL
 * seed and ships bundled in the app). Content rules, enforced by
 * src/lib/__tests__/seed.test.ts:
 * - Honest prep times for a real Indian kitchen, not recipe-site times.
 * - effort_score is about attention, not minutes: 1 assemble,
 *   2 light cooking, 3 full cooking.
 * - method_steps ≤ 6, sentence case, Pravah voice.
 * - Basic masala-dabba spices are assumed and never listed as
 *   ingredient dependencies.
 * - Dishes tagged 'leftover-transform' exist as transformation
 *   outputs and never enter the daily planner pool.
 */
import type { Dish, DishIngredient, DishTag, EffortScore, MealSlotName } from '@/types/domain';
import { ING } from './ingredients';
import { seedId } from './ids';

let counter = 0;

interface DishSpec {
  name: string;
  slots: (MealSlotName | 'any')[];
  prep: number;
  effort: EffortScore;
  protein: number;
  calories: number;
  needs: [(typeof ING)[keyof typeof ING], string][];
  steps: string[];
  tags?: DishTag[];
}

function dish(spec: DishSpec): Dish {
  counter += 1;
  if (spec.steps.length > 6) {
    throw new Error(`Dish "${spec.name}" has more than 6 method steps`);
  }
  const ingredients: DishIngredient[] = spec.needs.map(([ingredient, qty_hint]) => ({
    ingredient_id: ingredient.id,
    qty_hint,
  }));
  return {
    id: seedId('dish', counter),
    name: spec.name,
    slot_tags: spec.slots,
    prep_minutes: spec.prep,
    effort_score: spec.effort,
    protein_g: spec.protein,
    calories: spec.calories,
    ingredients,
    method_steps: spec.steps,
    tags: spec.tags ?? [],
  };
}

export const DISH = {
  // ---------- Breakfasts ----------
  poha: dish({
    name: 'kanda poha',
    slots: ['breakfast'],
    prep: 15,
    effort: 2,
    protein: 8,
    calories: 320,
    needs: [
      [ING.poha, '1.5 cups'],
      [ING.onions, '1 medium'],
      [ING.peanuts, 'a handful'],
      [ING.oil, '1 tbsp'],
      [ING.lemon, 'half'],
    ],
    steps: [
      'Rinse the poha in a colander and let it sit.',
      'Heat oil, crackle mustard seeds, add peanuts and sliced onion.',
      'Once the onion softens, add turmeric and salt.',
      'Fold in the poha and steam for two minutes, lid on.',
      'Finish with lemon juice.',
    ],
    tags: ['budget'],
  }),
  vegUpma: dish({
    name: 'vegetable upma',
    slots: ['breakfast'],
    prep: 20,
    effort: 2,
    protein: 9,
    calories: 350,
    needs: [
      [ING.suji, '1 cup'],
      [ING.onions, '1 small'],
      [ING.carrots, '1'],
      [ING.greenBeans, 'a handful'],
      [ING.oil, '1.5 tbsp'],
    ],
    steps: [
      'Dry-roast the suji until it smells nutty, then set aside.',
      'Heat oil, crackle mustard seeds, add onion and chopped vegetables.',
      'Pour in two cups of hot water with salt and bring to a boil.',
      'Stream in the suji while stirring, then cook covered for three minutes.',
    ],
    tags: ['budget'],
  }),
  besanCheela: dish({
    name: 'besan cheela',
    slots: ['breakfast'],
    prep: 15,
    effort: 2,
    protein: 12,
    calories: 280,
    needs: [
      [ING.besan, '1 cup'],
      [ING.onions, '1 small'],
      [ING.tomatoes, '1'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Whisk besan with water, salt and ajwain into a pourable batter.',
      'Stir in chopped onion, tomato and coriander.',
      'Ladle onto a hot tawa and spread like a dosa.',
      'Drizzle oil around the edges and cook both sides golden.',
    ],
    tags: ['budget'],
  }),
  masalaOats: dish({
    name: 'masala oats',
    slots: ['breakfast'],
    prep: 10,
    effort: 2,
    protein: 11,
    calories: 300,
    needs: [
      [ING.oats, '1 cup'],
      [ING.onions, '1 small'],
      [ING.tomatoes, '1'],
      [ING.peas, 'a handful'],
    ],
    steps: [
      'Sauté onion, tomato and peas with a pinch of turmeric.',
      'Add oats and two cups of water.',
      'Simmer for four minutes until creamy, season and serve.',
    ],
    tags: ['budget'],
  }),
  eggBhurjiRoti: dish({
    name: 'egg bhurji with roti',
    slots: ['breakfast', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 16,
    calories: 380,
    needs: [
      [ING.eggs, '3'],
      [ING.onions, '1 medium'],
      [ING.tomatoes, '1'],
      [ING.atta, 'for 2 rotis'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Soften onion in oil, then add tomato and a pinch of turmeric.',
      'Crack in the eggs and scramble on medium heat.',
      'Season with salt and garam masala.',
      'Serve hot with fresh rotis.',
    ],
  }),
  curdBananaBowl: dish({
    name: 'curd and banana bowl',
    slots: ['breakfast', 'any'],
    prep: 3,
    effort: 1,
    protein: 9,
    calories: 250,
    needs: [
      [ING.curd, '1 cup'],
      [ING.bananas, '1'],
    ],
    steps: [
      'Whisk the curd until smooth.',
      'Slice in the banana and add a spoon of sugar or jaggery.',
    ],
    tags: ['no-cook', 'budget', 'vrat-safe'],
  }),
  sproutsChaat: dish({
    name: 'sprouts chaat',
    slots: ['breakfast', 'any'],
    prep: 10,
    effort: 1,
    protein: 14,
    calories: 220,
    needs: [
      [ING.sprouts, '1.5 cups'],
      [ING.onions, '1 small'],
      [ING.tomatoes, '1'],
      [ING.lemon, 'half'],
    ],
    steps: [
      'Toss the sprouts with chopped onion and tomato.',
      'Season with chaat masala, salt and lemon juice.',
      'Top with coriander if you have it.',
    ],
    tags: ['no-cook', 'budget'],
  }),
  alooParatha: dish({
    name: 'aloo paratha with curd',
    slots: ['breakfast'],
    prep: 30,
    effort: 3,
    protein: 10,
    calories: 450,
    needs: [
      [ING.atta, 'for 2 parathas'],
      [ING.potatoes, '2 boiled'],
      [ING.ghee, '1 tbsp'],
      [ING.curd, '1 cup'],
    ],
    steps: [
      'Mash boiled potatoes with salt, chilli and coriander.',
      'Knead a soft atta dough and rest it ten minutes.',
      'Stuff, roll, and roast each paratha with ghee until golden.',
      'Serve with a bowl of curd.',
    ],
  }),
  breadOmelette: dish({
    name: 'bread omelette',
    slots: ['breakfast'],
    prep: 10,
    effort: 2,
    protein: 14,
    calories: 350,
    needs: [
      [ING.eggs, '2'],
      [ING.bread, '2 slices'],
      [ING.onions, '1 small'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Beat the eggs with chopped onion, chilli and salt.',
      'Pour into a hot oiled pan.',
      'Press the bread slices into the setting egg and flip once.',
    ],
    tags: ['budget'],
  }),

  // ---------- Lunches ----------
  dalTadkaRice: dish({
    name: 'dal tadka with rice',
    slots: ['lunch', 'dinner'],
    prep: 35,
    effort: 3,
    protein: 18,
    calories: 520,
    needs: [
      [ING.dal, '1 cup'],
      [ING.rice, '1 cup'],
      [ING.onions, '1'],
      [ING.tomatoes, '1'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Pressure-cook the dal with turmeric and salt.',
      'Cook the rice alongside.',
      'Make a tadka of ghee, jeera, onion and tomato.',
      'Pour the tadka over the dal and simmer five minutes.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  rajmaChawal: dish({
    name: 'rajma chawal',
    slots: ['lunch'],
    prep: 45,
    effort: 3,
    protein: 19,
    calories: 560,
    needs: [
      [ING.rajma, '1 cup soaked'],
      [ING.rice, '1 cup'],
      [ING.onions, '2'],
      [ING.tomatoes, '2'],
      [ING.oil, '2 tbsp'],
    ],
    steps: [
      'Pressure-cook soaked rajma until soft.',
      'Brown onions in oil, add tomato purée and the masalas.',
      'Add the rajma and simmer for fifteen minutes.',
      'Serve over fresh rice.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  chanaMasalaRice: dish({
    name: 'chana masala with rice',
    slots: ['lunch'],
    prep: 45,
    effort: 3,
    protein: 17,
    calories: 540,
    needs: [
      [ING.chana, '1 cup soaked'],
      [ING.rice, '1 cup'],
      [ING.onions, '2'],
      [ING.tomatoes, '2'],
      [ING.oil, '2 tbsp'],
    ],
    steps: [
      'Pressure-cook the soaked chana until tender.',
      'Cook down onions, then tomatoes and masalas into a thick base.',
      'Fold in the chana and simmer ten minutes.',
      'Serve with rice and a wedge of lemon.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  vegKhichdi: dish({
    name: 'vegetable khichdi',
    slots: ['lunch', 'dinner'],
    prep: 30,
    effort: 2,
    protein: 14,
    calories: 450,
    needs: [
      [ING.rice, '0.5 cup'],
      [ING.dal, '0.5 cup'],
      [ING.carrots, '1'],
      [ING.peas, 'a handful'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Rinse rice and dal together.',
      'Sauté jeera and vegetables in ghee.',
      'Add rice, dal, turmeric, salt and four cups of water.',
      'Pressure-cook for three whistles and rest.',
    ],
    tags: ['leftover-friendly', 'budget', 'recovery'],
  }),
  paneerBhurjiRoti: dish({
    name: 'paneer bhurji with roti',
    slots: ['lunch', 'dinner'],
    prep: 20,
    effort: 2,
    protein: 22,
    calories: 480,
    needs: [
      [ING.paneer, '150 g'],
      [ING.onions, '1'],
      [ING.tomatoes, '1'],
      [ING.atta, 'for 2 rotis'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Soften onion in oil, add tomato and the masalas.',
      'Crumble in the paneer and toss for three minutes.',
      'Finish with coriander and serve with rotis.',
    ],
  }),
  curdRice: dish({
    name: 'curd rice',
    slots: ['lunch', 'dinner', 'any'],
    prep: 10,
    effort: 1,
    protein: 9,
    calories: 380,
    needs: [
      [ING.rice, '1.5 cups cooked'],
      [ING.curd, '1 cup'],
    ],
    steps: [
      'Mash warm rice lightly and mix in the curd with salt.',
      'If you like, temper mustard seeds and curry leaves in a little oil and pour over.',
    ],
    tags: ['no-cook', 'budget', 'recovery'],
  }),
  lemonRice: dish({
    name: 'lemon rice',
    slots: ['lunch'],
    prep: 15,
    effort: 2,
    protein: 7,
    calories: 420,
    needs: [
      [ING.rice, '1.5 cups cooked'],
      [ING.lemon, '1'],
      [ING.peanuts, 'a handful'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Temper mustard seeds, peanuts and curry leaves in oil.',
      'Add turmeric, then the rice, and toss gently.',
      'Squeeze in the lemon off the heat and season.',
    ],
    tags: ['budget'],
  }),
  mixedVegRoti: dish({
    name: 'mixed veg sabzi with roti',
    slots: ['lunch', 'dinner'],
    prep: 30,
    effort: 3,
    protein: 9,
    calories: 430,
    needs: [
      [ING.cauliflower, 'half a head'],
      [ING.potatoes, '1'],
      [ING.peas, 'a handful'],
      [ING.atta, 'for 3 rotis'],
      [ING.oil, '1.5 tbsp'],
    ],
    steps: [
      'Sauté jeera, then the chopped vegetables with turmeric and salt.',
      'Cover and cook on low until tender, stirring twice.',
      'Sprinkle garam masala.',
      'Serve with fresh rotis.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  palakPaneer: dish({
    name: 'palak paneer with roti',
    slots: ['lunch', 'dinner'],
    prep: 35,
    effort: 3,
    protein: 20,
    calories: 490,
    needs: [
      [ING.palak, '1 bunch'],
      [ING.paneer, '150 g'],
      [ING.onions, '1'],
      [ING.atta, 'for 2 rotis'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Blanch the palak and blend to a purée.',
      'Sauté onion, garlic and the masalas in ghee.',
      'Add the purée, simmer, then slide in paneer cubes.',
      'Serve with rotis.',
    ],
    tags: ['leftover-friendly'],
  }),

  // ---------- Dinners ----------
  moongKhichdi: dish({
    name: 'moong dal khichdi',
    slots: ['dinner'],
    prep: 25,
    effort: 2,
    protein: 13,
    calories: 420,
    needs: [
      [ING.moong, '0.5 cup'],
      [ING.rice, '0.5 cup'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Rinse moong dal and rice together.',
      'Sauté jeera and hing in ghee, add the grains.',
      'Add water, turmeric and salt; pressure-cook three whistles.',
      'Serve with a spoon of ghee on top.',
    ],
    tags: ['leftover-friendly', 'budget', 'recovery'],
  }),
  chickenCurryRice: dish({
    name: 'chicken curry with rice',
    slots: ['dinner', 'lunch'],
    prep: 45,
    effort: 3,
    protein: 32,
    calories: 580,
    needs: [
      [ING.chicken, '300 g'],
      [ING.onions, '2'],
      [ING.tomatoes, '2'],
      [ING.curd, '2 tbsp'],
      [ING.rice, '1 cup'],
    ],
    steps: [
      'Brown sliced onions, then add ginger-garlic and the masalas.',
      'Add tomatoes and cook until the oil separates.',
      'Add chicken and sear, then whisk in curd and a cup of water.',
      'Simmer covered for twenty minutes.',
      'Serve with rice.',
    ],
    tags: ['leftover-friendly'],
  }),
  eggCurryRice: dish({
    name: 'egg curry with rice',
    slots: ['dinner'],
    prep: 30,
    effort: 3,
    protein: 18,
    calories: 510,
    needs: [
      [ING.eggs, '3 boiled'],
      [ING.onions, '1'],
      [ING.tomatoes, '2'],
      [ING.rice, '1 cup'],
      [ING.oil, '1.5 tbsp'],
    ],
    steps: [
      'Boil the eggs while the rice cooks.',
      'Make an onion-tomato masala base.',
      'Halve the eggs and slip them into the simmering gravy.',
      'Serve over rice.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  laukiRoti: dish({
    name: 'lauki sabzi with roti',
    slots: ['dinner'],
    prep: 30,
    effort: 3,
    protein: 8,
    calories: 380,
    needs: [
      [ING.lauki, '1 small'],
      [ING.tomatoes, '1'],
      [ING.atta, 'for 3 rotis'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Temper jeera, add diced lauki and tomato.',
      'Season with turmeric and salt, cover and cook until soft.',
      'Mash lightly and finish with coriander.',
      'Serve with rotis.',
    ],
    tags: ['budget', 'recovery'],
  }),
  bhindiRoti: dish({
    name: 'bhindi sabzi with roti',
    slots: ['dinner', 'lunch'],
    prep: 25,
    effort: 3,
    protein: 7,
    calories: 400,
    needs: [
      [ING.bhindi, '250 g'],
      [ING.onions, '1'],
      [ING.atta, 'for 3 rotis'],
      [ING.oil, '1.5 tbsp'],
    ],
    steps: [
      'Dry the bhindi well and chop.',
      'Sauté on medium-high without crowding the pan.',
      'Add sliced onion, salt and the masalas; cook until the stickiness goes.',
      'Serve with rotis.',
    ],
  }),
  matarPaneer: dish({
    name: 'matar paneer with roti',
    slots: ['dinner', 'lunch'],
    prep: 35,
    effort: 3,
    protein: 19,
    calories: 500,
    needs: [
      [ING.paneer, '150 g'],
      [ING.peas, '1 cup'],
      [ING.onions, '1'],
      [ING.tomatoes, '2'],
      [ING.atta, 'for 2 rotis'],
    ],
    steps: [
      'Blend onion and tomato into a smooth masala and cook it down in oil.',
      'Add peas with half a cup of water and simmer.',
      'Slide in the paneer and cook five more minutes.',
      'Serve with rotis.',
    ],
    tags: ['leftover-friendly'],
  }),
  soyaCurryRice: dish({
    name: 'soya chunk curry with rice',
    slots: ['dinner'],
    prep: 30,
    effort: 3,
    protein: 26,
    calories: 480,
    needs: [
      [ING.soyaChunks, '1 cup'],
      [ING.onions, '1'],
      [ING.tomatoes, '2'],
      [ING.rice, '1 cup'],
      [ING.oil, '1.5 tbsp'],
    ],
    steps: [
      'Soak the soya chunks in hot salted water, then squeeze dry.',
      'Cook an onion-tomato masala until glossy.',
      'Add the chunks and a cup of water; simmer ten minutes.',
      'Serve with rice.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),
  grilledPaneerVeg: dish({
    name: 'grilled paneer with sautéed veg',
    slots: ['dinner'],
    prep: 20,
    effort: 2,
    protein: 24,
    calories: 420,
    needs: [
      [ING.paneer, '200 g'],
      [ING.capsicum, '1'],
      [ING.onions, '1'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Rub paneer slabs with salt, chilli and turmeric.',
      'Sear on a hot pan until golden on both sides.',
      'Sauté capsicum and onion in the same pan.',
      'Plate together with a squeeze of lemon.',
    ],
  }),
  tomatoDalRoti: dish({
    name: 'tomato dal with roti',
    slots: ['dinner', 'lunch'],
    prep: 30,
    effort: 3,
    protein: 15,
    calories: 440,
    needs: [
      [ING.dal, '1 cup'],
      [ING.tomatoes, '2'],
      [ING.atta, 'for 2 rotis'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Pressure-cook dal with tomatoes, turmeric and salt.',
      'Temper jeera, garlic and chilli in ghee; pour it over.',
      'Simmer five minutes.',
      'Serve with rotis.',
    ],
    tags: ['leftover-friendly', 'budget'],
  }),

  // ---------- Staples-only floor dishes ----------
  // Every ingredient below is one of the 12 canonical staples, so the
  // planner's last-resort fallback always has a real dish per slot.
  andaRotiWrap: dish({
    name: 'anda roti wrap',
    slots: ['breakfast', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 15,
    calories: 390,
    needs: [
      [ING.eggs, '2'],
      [ING.onions, '1 small'],
      [ING.atta, 'for 2 rotis'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Make two rotis, or warm yesterday’s.',
      'Scramble the eggs with onion, salt and chilli.',
      'Roll the bhurji inside the rotis and pan-press for a minute.',
    ],
    tags: ['budget'],
  }),
  attaHalwa: dish({
    name: 'atta halwa with chai',
    slots: ['breakfast'],
    prep: 15,
    effort: 2,
    protein: 7,
    calories: 380,
    needs: [
      [ING.atta, '0.5 cup'],
      [ING.ghee, '2 tbsp'],
      [ING.sugar, '2 tbsp'],
      [ING.milk, '1 cup'],
      [ING.tea, 'for 1 cup'],
    ],
    steps: [
      'Roast the atta in ghee until it smells nutty and turns golden.',
      'Add warm milk and sugar, stirring until it thickens.',
      'Brew your chai alongside and sit down with both.',
    ],
    tags: ['budget'],
  }),

  // ---------- No-cook & assemble (any slot) ----------
  fruitCurdBowl: dish({
    name: 'seasonal fruit and curd bowl',
    slots: ['any', 'breakfast'],
    prep: 5,
    effort: 1,
    protein: 8,
    calories: 260,
    needs: [
      [ING.curd, '1 cup'],
      [ING.papaya, '1 cup chopped'],
      [ING.bananas, '1'],
    ],
    steps: [
      'Chop whatever fruit is in the kitchen.',
      'Fold into whisked curd with a little sugar or jaggery.',
    ],
    tags: ['no-cook', 'vrat-safe'],
  }),
  pbBananaSandwich: dish({
    name: 'peanut butter banana sandwich',
    slots: ['any', 'breakfast'],
    prep: 5,
    effort: 1,
    protein: 11,
    calories: 340,
    needs: [
      [ING.bread, '2 slices'],
      [ING.peanutButter, '2 tbsp'],
      [ING.bananas, '1'],
    ],
    steps: ['Spread the peanut butter generously.', 'Layer banana slices, close, and halve.'],
    tags: ['no-cook'],
  }),
  kachumberBowl: dish({
    name: 'kachumber chaat bowl',
    slots: ['any'],
    prep: 8,
    effort: 1,
    protein: 4,
    calories: 150,
    needs: [
      [ING.cucumber, '1'],
      [ING.tomatoes, '1'],
      [ING.onions, '1 small'],
      [ING.lemon, 'half'],
    ],
    steps: [
      'Dice cucumber, tomato and onion evenly.',
      'Toss with salt, chaat masala and lemon juice.',
    ],
    tags: ['no-cook', 'budget'],
  }),
  dahiChiwda: dish({
    name: 'dahi chiwda',
    slots: ['any', 'breakfast'],
    prep: 5,
    effort: 1,
    protein: 7,
    calories: 280,
    needs: [
      [ING.poha, '1 cup'],
      [ING.curd, '1 cup'],
      [ING.sugar, '1 tsp'],
    ],
    steps: [
      'Rinse the poha and let it soften for two minutes.',
      'Stir into curd with sugar or jaggery and a pinch of salt.',
    ],
    tags: ['no-cook', 'budget', 'vrat-safe'],
  }),

  // ---------- Leftover transformation outputs ----------
  dalParatha: dish({
    name: 'dal paratha',
    slots: ['breakfast', 'lunch'],
    prep: 15,
    effort: 2,
    protein: 11,
    calories: 380,
    needs: [
      [ING.atta, '1 cup'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Knead the leftover dal straight into atta — no extra water.',
      'Rest the dough five minutes.',
      'Roll out parathas and roast with oil until golden.',
      'Serve with curd or pickle.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  dalTadkaBowl: dish({
    name: 'dal tadka rice bowl',
    slots: ['lunch', 'dinner'],
    prep: 12,
    effort: 2,
    protein: 16,
    calories: 460,
    needs: [
      [ING.rice, '1 cup'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Warm the leftover dal with a splash of water.',
      'Make a fresh tadka of ghee, jeera and chilli; pour it over.',
      'Serve on hot rice.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  dalCheela: dish({
    name: 'dal cheela',
    slots: ['breakfast'],
    prep: 15,
    effort: 2,
    protein: 13,
    calories: 320,
    needs: [
      [ING.atta, '0.5 cup'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Whisk the leftover dal with atta into a pourable batter.',
      'Season with salt, chilli and coriander.',
      'Spread on a hot tawa and cook both sides with a little oil.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  dalShorba: dish({
    name: 'dal shorba',
    slots: ['dinner', 'any'],
    prep: 10,
    effort: 1,
    protein: 9,
    calories: 180,
    needs: [[ING.ghee, '2 tsp']],
    steps: [
      'Thin the leftover dal with hot water to soup consistency.',
      'Temper jeera and garlic in ghee; pour over.',
      'Simmer three minutes and finish with lemon.',
    ],
    tags: ['leftover-transform', 'recovery', 'budget'],
  }),
  dalKhichdiRefresh: dish({
    name: 'dal khichdi refresh',
    slots: ['dinner'],
    prep: 15,
    effort: 2,
    protein: 14,
    calories: 420,
    needs: [
      [ING.rice, '0.5 cup'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Simmer the leftover dal with rinsed rice and two cups of water.',
      'Season with turmeric and salt.',
      'Cook covered until the rice is soft, then finish with ghee.',
    ],
    tags: ['leftover-transform', 'recovery', 'budget'],
  }),
  sabziParatha: dish({
    name: 'sabzi paratha',
    slots: ['breakfast', 'lunch'],
    prep: 15,
    effort: 2,
    protein: 9,
    calories: 390,
    needs: [
      [ING.atta, '1 cup'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Mash the leftover sabzi well.',
      'Knead it into atta — the sabzi replaces the water.',
      'Roll and roast parathas with oil until crisp-edged.',
      'Serve with curd.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  sabziFrankie: dish({
    name: 'sabzi frankie roll',
    slots: ['lunch', 'dinner'],
    prep: 12,
    effort: 2,
    protein: 8,
    calories: 360,
    needs: [
      [ING.atta, 'for 2 rotis'],
      [ING.onions, '1 small'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Make two fresh rotis, or warm yesterday’s.',
      'Heat the sabzi until it dries out a little.',
      'Spread on the roti with sliced onion and chaat masala.',
      'Roll tight and pan-press for a minute.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  sabziPulao: dish({
    name: 'sabzi pulao',
    slots: ['lunch', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 8,
    calories: 430,
    needs: [
      [ING.rice, '1 cup'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Heat oil, crackle jeera, and add the leftover sabzi.',
      'Fold in cooked rice and toss on high heat.',
      'Adjust salt and finish with coriander.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  sabziEggScramble: dish({
    name: 'sabzi egg scramble',
    slots: ['breakfast', 'dinner'],
    prep: 10,
    effort: 2,
    protein: 15,
    calories: 330,
    needs: [
      [ING.eggs, '2'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Heat the leftover sabzi in a little oil, breaking it down.',
      'Crack in the eggs and scramble until just set.',
      'Season and serve with toast or roti.',
    ],
    tags: ['leftover-transform'],
  }),
  sabziChaat: dish({
    name: 'crispy sabzi chaat',
    slots: ['any'],
    prep: 12,
    effort: 2,
    protein: 6,
    calories: 280,
    needs: [
      [ING.onions, '1 small'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Pan-crisp the leftover sabzi in oil until the edges brown.',
      'Top with chopped onion, chaat masala and lemon.',
      'Add curd on top if you have it.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  jeeraGheeRice: dish({
    name: 'jeera ghee rice',
    slots: ['lunch', 'dinner'],
    prep: 8,
    effort: 1,
    protein: 6,
    calories: 380,
    needs: [[ING.ghee, '1 tbsp']],
    steps: [
      'Heat ghee and crackle jeera generously.',
      'Add the leftover rice and toss until glossy and hot.',
      'Season with salt; serve with curd or dal.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  eggFriedRice: dish({
    name: 'desi egg fried rice',
    slots: ['lunch', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 17,
    calories: 480,
    needs: [
      [ING.eggs, '2'],
      [ING.onions, '1'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Scramble the eggs in hot oil and set aside.',
      'Sauté onion and any vegetables on high heat.',
      'Add the leftover rice, eggs, salt and pepper; toss hard.',
      'Finish with a dash of lemon.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  quickKheer: dish({
    name: 'quick rice kheer',
    slots: ['any'],
    prep: 15,
    effort: 2,
    protein: 8,
    calories: 320,
    needs: [
      [ING.milk, '2 cups'],
      [ING.sugar, '2 tbsp'],
    ],
    steps: [
      'Simmer the leftover rice in milk, mashing as it thickens.',
      'Sweeten with sugar and a pinch of cardamom.',
      'Serve warm or chilled.',
    ],
    tags: ['leftover-transform', 'vrat-safe'],
  }),
  riceDalBowl: dish({
    name: 'comfort dal-rice bowl',
    slots: ['dinner'],
    prep: 12,
    effort: 1,
    protein: 13,
    calories: 430,
    needs: [
      [ING.dal, '1 cup cooked'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Warm the leftover rice and dal together with a splash of water.',
      'Top with ghee and a pinch of salt.',
      'Eat from the bowl — comfort first.',
    ],
    tags: ['leftover-transform', 'recovery', 'budget'],
  }),
  churmaRoti: dish({
    name: 'ghee-sugar churma roti',
    slots: ['any'],
    prep: 8,
    effort: 1,
    protein: 5,
    calories: 340,
    needs: [
      [ING.ghee, '1 tbsp'],
      [ING.sugar, '1 tbsp'],
    ],
    steps: [
      'Crisp the leftover rotis on a tawa.',
      'Crush into pieces while warm.',
      'Toss with melted ghee and sugar or jaggery.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  kothuRoti: dish({
    name: 'kothu roti with egg',
    slots: ['dinner'],
    prep: 15,
    effort: 2,
    protein: 14,
    calories: 420,
    needs: [
      [ING.eggs, '2'],
      [ING.onions, '1'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Shred the leftover rotis into ribbons.',
      'Sauté onion, then scramble in the eggs.',
      'Add the roti ribbons and toss on high heat with the masalas.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  rotiUpma: dish({
    name: 'roti upma',
    slots: ['breakfast'],
    prep: 12,
    effort: 2,
    protein: 7,
    calories: 330,
    needs: [
      [ING.onions, '1'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Tear the leftover rotis into small pieces.',
      'Temper mustard seeds and onion in oil.',
      'Toss in the roti with turmeric, salt and a splash of water.',
      'Cover for two minutes so it softens.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  milkRotiBowl: dish({
    name: 'warm milk-roti bowl',
    slots: ['any'],
    prep: 5,
    effort: 1,
    protein: 9,
    calories: 310,
    needs: [
      [ING.milk, '1.5 cups'],
      [ING.sugar, '1 tbsp'],
    ],
    steps: [
      'Warm the milk with sugar.',
      'Crumble in the leftover roti and let it soak for two minutes.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  dalRotiTacos: dish({
    name: 'dal-stuffed roti tacos',
    slots: ['lunch', 'dinner'],
    prep: 12,
    effort: 2,
    protein: 12,
    calories: 390,
    needs: [
      [ING.dal, '1 cup cooked'],
      [ING.onions, '1 small'],
    ],
    steps: [
      'Thicken the leftover dal in a pan until scoopable.',
      'Warm the rotis and fold like tacos.',
      'Fill with dal, chopped onion and a hit of chaat masala.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  curryRiceBowl: dish({
    name: 'curry rice bowl',
    slots: ['lunch', 'dinner'],
    prep: 10,
    effort: 1,
    protein: 14,
    calories: 450,
    needs: [[ING.rice, '1 cup']],
    steps: [
      'Warm the leftover curry — add a splash of water if thick.',
      'Serve generously over hot rice.',
      'Top with raw onion and lemon.',
    ],
    tags: ['leftover-transform'],
  }),
  curryParatha: dish({
    name: 'curry paratha',
    slots: ['breakfast', 'lunch'],
    prep: 15,
    effort: 2,
    protein: 10,
    calories: 400,
    needs: [
      [ING.atta, '1 cup'],
      [ING.oil, '1 tbsp'],
    ],
    steps: [
      'Reduce the leftover curry until thick.',
      'Knead it into atta for a spiced dough.',
      'Roll and roast parathas with oil.',
    ],
    tags: ['leftover-transform', 'budget'],
  }),
  curryPulao: dish({
    name: 'curry pulao',
    slots: ['lunch', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 12,
    calories: 470,
    needs: [
      [ING.rice, '1 cup'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Heat the leftover curry in a wide pan.',
      'Fold in cooked rice and a splash of water.',
      'Cover and steam for five minutes, then fluff.',
    ],
    tags: ['leftover-transform'],
  }),
  curryEggRefresh: dish({
    name: 'egg-drop curry refresh',
    slots: ['dinner'],
    prep: 15,
    effort: 2,
    protein: 16,
    calories: 380,
    needs: [[ING.eggs, '2']],
    steps: [
      'Bring the leftover curry to a gentle simmer.',
      'Slip in boiled egg halves — or poach eggs straight in the gravy.',
      'Simmer five minutes and serve with rice or roti.',
    ],
    tags: ['leftover-transform'],
  }),
  curryShorba: dish({
    name: 'curry shorba',
    slots: ['any', 'dinner'],
    prep: 10,
    effort: 1,
    protein: 8,
    calories: 220,
    needs: [[ING.ghee, '2 tsp']],
    steps: [
      'Thin the leftover curry with hot water and bring to a simmer.',
      'Temper jeera in ghee and pour over.',
      'Sip warm with black pepper on top.',
    ],
    tags: ['leftover-transform', 'recovery'],
  }),
  paneerBhurjiRefresh: dish({
    name: 'paneer bhurji refresh',
    slots: ['breakfast', 'dinner'],
    prep: 10,
    effort: 2,
    protein: 18,
    calories: 350,
    needs: [
      [ING.onions, '1 small'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Crumble the leftover paneer dish into a hot oiled pan.',
      'Add chopped onion and toss until everything dries and browns a little.',
      'Finish with coriander and lemon.',
    ],
    tags: ['leftover-transform'],
  }),
  paneerParatha: dish({
    name: 'paneer paratha',
    slots: ['breakfast', 'lunch'],
    prep: 15,
    effort: 2,
    protein: 16,
    calories: 430,
    needs: [
      [ING.atta, '1 cup'],
      [ING.ghee, '1 tbsp'],
    ],
    steps: [
      'Mash the leftover paneer dish into a thick filling.',
      'Stuff into atta dough rounds.',
      'Roll gently and roast with ghee until golden.',
    ],
    tags: ['leftover-transform'],
  }),
  paneerRiceBowl: dish({
    name: 'paneer rice bowl',
    slots: ['lunch', 'dinner'],
    prep: 10,
    effort: 1,
    protein: 17,
    calories: 460,
    needs: [[ING.rice, '1 cup']],
    steps: [
      'Warm the leftover paneer dish with a splash of water.',
      'Spoon over hot rice.',
      'Top with raw onion rings.',
    ],
    tags: ['leftover-transform'],
  }),
  paneerKathiRoll: dish({
    name: 'paneer kathi roll',
    slots: ['lunch', 'dinner'],
    prep: 15,
    effort: 2,
    protein: 19,
    calories: 440,
    needs: [
      [ING.atta, 'for 2 rotis'],
      [ING.onions, '1 small'],
      [ING.oil, '2 tsp'],
    ],
    steps: [
      'Dry out the leftover paneer dish in a hot pan.',
      'Make fresh rotis or warm yesterday’s.',
      'Roll the paneer inside with onion and a squeeze of lemon.',
      'Pan-press the roll for a minute.',
    ],
    tags: ['leftover-transform'],
  }),
  creamyPaneerRefresh: dish({
    name: 'creamy paneer refresh',
    slots: ['dinner'],
    prep: 12,
    effort: 2,
    protein: 18,
    calories: 420,
    needs: [
      [ING.milk, '0.5 cup'],
      [ING.ghee, '2 tsp'],
    ],
    steps: [
      'Warm the leftover paneer dish in ghee.',
      'Stir in milk and simmer until the gravy turns silky.',
      'Serve with roti or rice.',
    ],
    tags: ['leftover-transform'],
  }),
} as const;

export type DishKey = keyof typeof DISH;

export const SEED_DISHES: Dish[] = Object.values(DISH);
